namespace SourceCode
{
    partial class Form1
    {
        /// <summary>
        /// Required designer variable.
        /// </summary>
        private System.ComponentModel.IContainer components = null;

        /// <summary>
        /// Clean up any resources being used.
        /// </summary>
        /// <param name="disposing">true if managed resources should be disposed; otherwise, false.</param>
        protected override void Dispose(bool disposing)
        {
            if (disposing && (components != null))
            {
                components.Dispose();
            }

            base.Dispose(disposing);
        }

        #region Windows Form Designer generated code

        /// <summary>
        /// Required method for Designer support - do not modify
        /// the contents of this method with the code editor.
        /// </summary>
        private void InitializeComponent()
        {
            this.tabControl1 = new System.Windows.Forms.TabControl();
            this.tabAddUsu = new System.Windows.Forms.TabPage();
            this.btnAgregarUsu = new System.Windows.Forms.Button();
            this.txtUserName = new System.Windows.Forms.TextBox();
            this.txtFullname = new System.Windows.Forms.TextBox();
            this.groupBox1 = new System.Windows.Forms.GroupBox();
            this.rdbUsuario = new System.Windows.Forms.RadioButton();
            this.rdbAdmin = new System.Windows.Forms.RadioButton();
            this.label2 = new System.Windows.Forms.Label();
            this.label1 = new System.Windows.Forms.Label();
            this.tabDeleteUsu = new System.Windows.Forms.TabPage();
            this.dgvVerUsuarios = new System.Windows.Forms.DataGridView();
            this.btnEliminarUsu = new System.Windows.Forms.Button();
            this.cmbEliminarUsu = new System.Windows.Forms.ComboBox();
            this.label3 = new System.Windows.Forms.Label();
            this.tabAddBussines = new System.Windows.Forms.TabPage();
            this.btnAgregarNegocio = new System.Windows.Forms.Button();
            this.txtDescripcion = new System.Windows.Forms.TextBox();
            this.txtNegocio = new System.Windows.Forms.TextBox();
            this.label5 = new System.Windows.Forms.Label();
            this.label4 = new System.Windows.Forms.Label();
            this.tabDeleteBussines = new System.Windows.Forms.TabPage();
            this.dataGridView1 = new System.Windows.Forms.DataGridView();
            this.btnEliminarNegocio = new System.Windows.Forms.Button();
            this.cmbEliminarNegocio = new System.Windows.Forms.ComboBox();
            this.label6 = new System.Windows.Forms.Label();
            this.tabAddProduct = new System.Windows.Forms.TabPage();
            this.btnAgreagarProducto = new System.Windows.Forms.Button();
            this.txtNombreProducto = new System.Windows.Forms.TextBox();
            this.label8 = new System.Windows.Forms.Label();
            this.cmbAddProduct = new System.Windows.Forms.ComboBox();
            this.label7 = new System.Windows.Forms.Label();
            this.tabDeleteProduct = new System.Windows.Forms.TabPage();
            this.combEliminarProd = new System.Windows.Forms.ComboBox();
            this.dgvVerProductos = new System.Windows.Forms.DataGridView();
            this.btnEliminarProducto = new System.Windows.Forms.Button();
            this.label9 = new System.Windows.Forms.Label();
            this.tabSeeOrders = new System.Windows.Forms.TabPage();
            this.dgvVerOrdenes = new System.Windows.Forms.DataGridView();
            this.tabAddAdress = new System.Windows.Forms.TabPage();
            this.dgvVerDirecciones = new System.Windows.Forms.DataGridView();
            this.btnAgregarDireccion = new System.Windows.Forms.Button();
            this.txtDireccion = new System.Windows.Forms.TextBox();
            this.label10 = new System.Windows.Forms.Label();
            this.tabModifyAdress = new System.Windows.Forms.TabPage();
            this.btnEliminarDirec = new System.Windows.Forms.Button();
            this.txtEliminarDirec = new System.Windows.Forms.TextBox();
            this.label13 = new System.Windows.Forms.Label();
            this.btnMofificarDirec = new System.Windows.Forms.Button();
            this.label12 = new System.Windows.Forms.Label();
            this.txtNuevaDirec = new System.Windows.Forms.TextBox();
            this.txtModificarDireccion = new System.Windows.Forms.TextBox();
            this.label11 = new System.Windows.Forms.Label();
            this.tabAddOrder = new System.Windows.Forms.TabPage();
            this.btnAgregarOrden = new System.Windows.Forms.Button();
            this.cmbAgregarProd = new System.Windows.Forms.ComboBox();
            this.label15 = new System.Windows.Forms.Label();
            this.txtAgregarOrden = new System.Windows.Forms.TextBox();
            this.label14 = new System.Windows.Forms.Label();
            this.tabDeleteOrder = new System.Windows.Forms.TabPage();
            this.dgvVerOrdenesPersonales = new System.Windows.Forms.DataGridView();
            this.btnEliminarOrden = new System.Windows.Forms.Button();
            this.label16 = new System.Windows.Forms.Label();
            this.textBox1 = new System.Windows.Forms.TextBox();
            this.tabControl1.SuspendLayout();
            this.tabAddUsu.SuspendLayout();
            this.groupBox1.SuspendLayout();
            this.tabDeleteUsu.SuspendLayout();
            ((System.ComponentModel.ISupportInitialize) (this.dgvVerUsuarios)).BeginInit();
            this.tabAddBussines.SuspendLayout();
            this.tabDeleteBussines.SuspendLayout();
            ((System.ComponentModel.ISupportInitialize) (this.dataGridView1)).BeginInit();
            this.tabAddProduct.SuspendLayout();
            this.tabDeleteProduct.SuspendLayout();
            ((System.ComponentModel.ISupportInitialize) (this.dgvVerProductos)).BeginInit();
            this.tabSeeOrders.SuspendLayout();
            ((System.ComponentModel.ISupportInitialize) (this.dgvVerOrdenes)).BeginInit();
            this.tabAddAdress.SuspendLayout();
            ((System.ComponentModel.ISupportInitialize) (this.dgvVerDirecciones)).BeginInit();
            this.tabModifyAdress.SuspendLayout();
            this.tabAddOrder.SuspendLayout();
            this.tabDeleteOrder.SuspendLayout();
            ((System.ComponentModel.ISupportInitialize) (this.dgvVerOrdenesPersonales)).BeginInit();
            this.SuspendLayout();
            this.tabControl1.Controls.Add(this.tabAddUsu);
            this.tabControl1.Controls.Add(this.tabDeleteUsu);
            this.tabControl1.Controls.Add(this.tabAddBussines);
            this.tabControl1.Controls.Add(this.tabDeleteBussines);
            this.tabControl1.Controls.Add(this.tabAddProduct);
            this.tabControl1.Controls.Add(this.tabDeleteProduct);
            this.tabControl1.Controls.Add(this.tabSeeOrders);
            this.tabControl1.Controls.Add(this.tabAddAdress);
            this.tabControl1.Controls.Add(this.tabModifyAdress);
            this.tabControl1.Controls.Add(this.tabAddOrder);
            this.tabControl1.Controls.Add(this.tabDeleteOrder);
            this.tabControl1.Location = new System.Drawing.Point(12, 3);
            this.tabControl1.Name = "tabControl1";
            this.tabControl1.SelectedIndex = 0;
            this.tabControl1.Size = new System.Drawing.Size(697, 431);
            this.tabControl1.TabIndex = 0;
            this.tabAddUsu.BackColor = System.Drawing.Color.FromArgb(((int) (((byte) (255)))), ((int) (((byte) (128)))), ((int) (((byte) (255)))));
            this.tabAddUsu.Controls.Add(this.btnAgregarUsu);
            this.tabAddUsu.Controls.Add(this.txtUserName);
            this.tabAddUsu.Controls.Add(this.txtFullname);
            this.tabAddUsu.Controls.Add(this.groupBox1);
            this.tabAddUsu.Controls.Add(this.label2);
            this.tabAddUsu.Controls.Add(this.label1);
            this.tabAddUsu.Location = new System.Drawing.Point(4, 22);
            this.tabAddUsu.Name = "tabAddUsu";
            this.tabAddUsu.Padding = new System.Windows.Forms.Padding(3);
            this.tabAddUsu.Size = new System.Drawing.Size(689, 405);
            this.tabAddUsu.TabIndex = 0;
            this.tabAddUsu.Text = "Agregar Usuario";
            this.btnAgregarUsu.BackColor = System.Drawing.Color.FromArgb(((int) (((byte) (192)))), ((int) (((byte) (0)))), ((int) (((byte) (192)))));
            this.btnAgregarUsu.Font = new System.Drawing.Font("Microsoft Sans Serif", 9.75F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte) (0)));
            this.btnAgregarUsu.ForeColor = System.Drawing.Color.White;
            this.btnAgregarUsu.Location = new System.Drawing.Point(260, 313);
            this.btnAgregarUsu.Name = "btnAgregarUsu";
            this.btnAgregarUsu.Size = new System.Drawing.Size(202, 63);
            this.btnAgregarUsu.TabIndex = 9;
            this.btnAgregarUsu.Text = "Agregar Usuario";
            this.btnAgregarUsu.UseVisualStyleBackColor = false;
            this.btnAgregarUsu.Click += new System.EventHandler(this.btnAgregarUsu_Click);
            this.txtUserName.Location = new System.Drawing.Point(211, 71);
            this.txtUserName.Name = "txtUserName";
            this.txtUserName.Size = new System.Drawing.Size(406, 20);
            this.txtUserName.TabIndex = 8;
            this.txtFullname.Location = new System.Drawing.Point(211, 12);
            this.txtFullname.Name = "txtFullname";
            this.txtFullname.Size = new System.Drawing.Size(406, 20);
            this.txtFullname.TabIndex = 7;
            this.groupBox1.Controls.Add(this.rdbUsuario);
            this.groupBox1.Controls.Add(this.rdbAdmin);
            this.groupBox1.Font = new System.Drawing.Font("Microsoft Sans Serif", 9.75F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte) (0)));
            this.groupBox1.Location = new System.Drawing.Point(265, 141);
            this.groupBox1.Name = "groupBox1";
            this.groupBox1.Size = new System.Drawing.Size(197, 140);
            this.groupBox1.TabIndex = 6;
            this.groupBox1.TabStop = false;
            this.groupBox1.Text = "Permisos";
            this.rdbUsuario.Font = new System.Drawing.Font("Microsoft Sans Serif", 9.75F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte) (0)));
            this.rdbUsuario.Location = new System.Drawing.Point(26, 85);
            this.rdbUsuario.Name = "rdbUsuario";
            this.rdbUsuario.Size = new System.Drawing.Size(161, 23);
            this.rdbUsuario.TabIndex = 5;
            this.rdbUsuario.TabStop = true;
            this.rdbUsuario.Text = "Usuario";
            this.rdbUsuario.UseVisualStyleBackColor = true;
            this.rdbAdmin.Font = new System.Drawing.Font("Microsoft Sans Serif", 9.75F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte) (0)));
            this.rdbAdmin.Location = new System.Drawing.Point(26, 31);
            this.rdbAdmin.Name = "rdbAdmin";
            this.rdbAdmin.Size = new System.Drawing.Size(161, 23);
            this.rdbAdmin.TabIndex = 4;
            this.rdbAdmin.TabStop = true;
            this.rdbAdmin.Text = "Administrador";
            this.rdbAdmin.UseVisualStyleBackColor = true;
            this.label2.Font = new System.Drawing.Font("Microsoft Sans Serif", 14.25F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte) (0)));
            this.label2.ForeColor = System.Drawing.Color.White;
            this.label2.Location = new System.Drawing.Point(18, 71);
            this.label2.Name = "label2";
            this.label2.Size = new System.Drawing.Size(182, 40);
            this.label2.TabIndex = 3;
            this.label2.Text = "Nombre de Usuario:";
            this.label1.Font = new System.Drawing.Font("Microsoft Sans Serif", 14.25F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte) (0)));
            this.label1.ForeColor = System.Drawing.Color.White;
            this.label1.Location = new System.Drawing.Point(18, 15);
            this.label1.Name = "label1";
            this.label1.Size = new System.Drawing.Size(171, 40);
            this.label1.TabIndex = 2;
            this.label1.Text = "Nombre Completo:";
            this.tabDeleteUsu.BackColor = System.Drawing.Color.FromArgb(((int) (((byte) (255)))), ((int) (((byte) (128)))), ((int) (((byte) (255)))));
            this.tabDeleteUsu.Controls.Add(this.dgvVerUsuarios);
            this.tabDeleteUsu.Controls.Add(this.btnEliminarUsu);
            this.tabDeleteUsu.Controls.Add(this.cmbEliminarUsu);
            this.tabDeleteUsu.Controls.Add(this.label3);
            this.tabDeleteUsu.Location = new System.Drawing.Point(4, 22);
            this.tabDeleteUsu.Name = "tabDeleteUsu";
            this.tabDeleteUsu.Padding = new System.Windows.Forms.Padding(3);
            this.tabDeleteUsu.Size = new System.Drawing.Size(689, 405);
            this.tabDeleteUsu.TabIndex = 1;
            this.tabDeleteUsu.Text = "Eliminar Usuario";
            this.dgvVerUsuarios.AllowUserToAddRows = false;
            this.dgvVerUsuarios.AllowUserToDeleteRows = false;
            this.dgvVerUsuarios.ColumnHeadersHeightSizeMode = System.Windows.Forms.DataGridViewColumnHeadersHeightSizeMode.AutoSize;
            this.dgvVerUsuarios.Location = new System.Drawing.Point(0, 139);
            this.dgvVerUsuarios.Name = "dgvVerUsuarios";
            this.dgvVerUsuarios.ReadOnly = true;
            this.dgvVerUsuarios.Size = new System.Drawing.Size(695, 265);
            this.dgvVerUsuarios.TabIndex = 11;
            this.btnEliminarUsu.BackColor = System.Drawing.Color.FromArgb(((int) (((byte) (192)))), ((int) (((byte) (0)))), ((int) (((byte) (192)))));
            this.btnEliminarUsu.Font = new System.Drawing.Font("Microsoft Sans Serif", 9.75F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte) (0)));
            this.btnEliminarUsu.ForeColor = System.Drawing.Color.White;
            this.btnEliminarUsu.Location = new System.Drawing.Point(293, 67);
            this.btnEliminarUsu.Name = "btnEliminarUsu";
            this.btnEliminarUsu.Size = new System.Drawing.Size(202, 57);
            this.btnEliminarUsu.TabIndex = 10;
            this.btnEliminarUsu.Text = "Eliminar Usuario";
            this.btnEliminarUsu.UseVisualStyleBackColor = false;
            this.btnEliminarUsu.Click += new System.EventHandler(this.btnEliminarUsu_Click);
            this.cmbEliminarUsu.FormattingEnabled = true;
            this.cmbEliminarUsu.Location = new System.Drawing.Point(219, 24);
            this.cmbEliminarUsu.Name = "cmbEliminarUsu";
            this.cmbEliminarUsu.Size = new System.Drawing.Size(364, 21);
            this.cmbEliminarUsu.TabIndex = 5;
            this.label3.Font = new System.Drawing.Font("Microsoft Sans Serif", 14.25F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte) (0)));
            this.label3.ForeColor = System.Drawing.Color.White;
            this.label3.Location = new System.Drawing.Point(16, 26);
            this.label3.Name = "label3";
            this.label3.Size = new System.Drawing.Size(182, 40);
            this.label3.TabIndex = 4;
            this.label3.Text = "Id de Usuario:";
            this.tabAddBussines.BackColor = System.Drawing.Color.FromArgb(((int) (((byte) (255)))), ((int) (((byte) (128)))), ((int) (((byte) (255)))));
            this.tabAddBussines.Controls.Add(this.btnAgregarNegocio);
            this.tabAddBussines.Controls.Add(this.txtDescripcion);
            this.tabAddBussines.Controls.Add(this.txtNegocio);
            this.tabAddBussines.Controls.Add(this.label5);
            this.tabAddBussines.Controls.Add(this.label4);
            this.tabAddBussines.Location = new System.Drawing.Point(4, 22);
            this.tabAddBussines.Name = "tabAddBussines";
            this.tabAddBussines.Padding = new System.Windows.Forms.Padding(3);
            this.tabAddBussines.Size = new System.Drawing.Size(689, 405);
            this.tabAddBussines.TabIndex = 2;
            this.tabAddBussines.Text = "Agregar Negocio";
            this.btnAgregarNegocio.BackColor = System.Drawing.Color.FromArgb(((int) (((byte) (192)))), ((int) (((byte) (0)))), ((int) (((byte) (192)))));
            this.btnAgregarNegocio.Font = new System.Drawing.Font("Microsoft Sans Serif", 9.75F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte) (0)));
            this.btnAgregarNegocio.ForeColor = System.Drawing.Color.White;
            this.btnAgregarNegocio.Location = new System.Drawing.Point(328, 251);
            this.btnAgregarNegocio.Name = "btnAgregarNegocio";
            this.btnAgregarNegocio.Size = new System.Drawing.Size(202, 57);
            this.btnAgregarNegocio.TabIndex = 11;
            this.btnAgregarNegocio.Text = "Agregar negocio";
            this.btnAgregarNegocio.UseVisualStyleBackColor = false;
            this.btnAgregarNegocio.Click += new System.EventHandler(this.btnAgregarNegocio_Click);
            this.txtDescripcion.Location = new System.Drawing.Point(250, 153);
            this.txtDescripcion.Name = "txtDescripcion";
            this.txtDescripcion.Size = new System.Drawing.Size(406, 20);
            this.txtDescripcion.TabIndex = 9;
            this.txtNegocio.Location = new System.Drawing.Point(250, 55);
            this.txtNegocio.Name = "txtNegocio";
            this.txtNegocio.Size = new System.Drawing.Size(406, 20);
            this.txtNegocio.TabIndex = 8;
            this.label5.Font = new System.Drawing.Font("Microsoft Sans Serif", 14.25F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte) (0)));
            this.label5.ForeColor = System.Drawing.Color.White;
            this.label5.Location = new System.Drawing.Point(45, 148);
            this.label5.Name = "label5";
            this.label5.Size = new System.Drawing.Size(182, 40);
            this.label5.TabIndex = 6;
            this.label5.Text = "Descripción:";
            this.label4.Font = new System.Drawing.Font("Microsoft Sans Serif", 14.25F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte) (0)));
            this.label4.ForeColor = System.Drawing.Color.White;
            this.label4.Location = new System.Drawing.Point(45, 50);
            this.label4.Name = "label4";
            this.label4.Size = new System.Drawing.Size(199, 40);
            this.label4.TabIndex = 5;
            this.label4.Text = "Nombre de negocio:";
            this.tabDeleteBussines.BackColor = System.Drawing.Color.FromArgb(((int) (((byte) (255)))), ((int) (((byte) (128)))), ((int) (((byte) (255)))));
            this.tabDeleteBussines.Controls.Add(this.dataGridView1);
            this.tabDeleteBussines.Controls.Add(this.btnEliminarNegocio);
            this.tabDeleteBussines.Controls.Add(this.cmbEliminarNegocio);
            this.tabDeleteBussines.Controls.Add(this.label6);
            this.tabDeleteBussines.Location = new System.Drawing.Point(4, 22);
            this.tabDeleteBussines.Name = "tabDeleteBussines";
            this.tabDeleteBussines.Padding = new System.Windows.Forms.Padding(3);
            this.tabDeleteBussines.Size = new System.Drawing.Size(689, 405);
            this.tabDeleteBussines.TabIndex = 3;
            this.tabDeleteBussines.Text = "Eliminar Negocio";
            this.dataGridView1.AllowUserToAddRows = false;
            this.dataGridView1.AllowUserToDeleteRows = false;
            this.dataGridView1.ColumnHeadersHeightSizeMode = System.Windows.Forms.DataGridViewColumnHeadersHeightSizeMode.AutoSize;
            this.dataGridView1.Location = new System.Drawing.Point(1, 140);
            this.dataGridView1.Name = "dataGridView1";
            this.dataGridView1.ReadOnly = true;
            this.dataGridView1.Size = new System.Drawing.Size(695, 265);
            this.dataGridView1.TabIndex = 12;
            this.btnEliminarNegocio.BackColor = System.Drawing.Color.FromArgb(((int) (((byte) (192)))), ((int) (((byte) (0)))), ((int) (((byte) (192)))));
            this.btnEliminarNegocio.Font = new System.Drawing.Font("Microsoft Sans Serif", 9.75F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte) (0)));
            this.btnEliminarNegocio.ForeColor = System.Drawing.Color.White;
            this.btnEliminarNegocio.Location = new System.Drawing.Point(327, 70);
            this.btnEliminarNegocio.Name = "btnEliminarNegocio";
            this.btnEliminarNegocio.Size = new System.Drawing.Size(202, 57);
            this.btnEliminarNegocio.TabIndex = 11;
            this.btnEliminarNegocio.Text = "Eliminar Negocio";
            this.btnEliminarNegocio.UseVisualStyleBackColor = false;
            this.btnEliminarNegocio.Click += new System.EventHandler(this.btnEliminarNegocio_Click);
            this.cmbEliminarNegocio.FormattingEnabled = true;
            this.cmbEliminarNegocio.Location = new System.Drawing.Point(261, 25);
            this.cmbEliminarNegocio.Name = "cmbEliminarNegocio";
            this.cmbEliminarNegocio.Size = new System.Drawing.Size(355, 21);
            this.cmbEliminarNegocio.TabIndex = 7;
            this.label6.Font = new System.Drawing.Font("Microsoft Sans Serif", 14.25F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte) (0)));
            this.label6.ForeColor = System.Drawing.Color.White;
            this.label6.Location = new System.Drawing.Point(28, 25);
            this.label6.Name = "label6";
            this.label6.Size = new System.Drawing.Size(199, 40);
            this.label6.TabIndex = 6;
            this.label6.Text = "Id de Negocio:";
            this.tabAddProduct.BackColor = System.Drawing.Color.FromArgb(((int) (((byte) (255)))), ((int) (((byte) (128)))), ((int) (((byte) (255)))));
            this.tabAddProduct.Controls.Add(this.btnAgreagarProducto);
            this.tabAddProduct.Controls.Add(this.txtNombreProducto);
            this.tabAddProduct.Controls.Add(this.label8);
            this.tabAddProduct.Controls.Add(this.cmbAddProduct);
            this.tabAddProduct.Controls.Add(this.label7);
            this.tabAddProduct.Location = new System.Drawing.Point(4, 22);
            this.tabAddProduct.Name = "tabAddProduct";
            this.tabAddProduct.Padding = new System.Windows.Forms.Padding(3);
            this.tabAddProduct.Size = new System.Drawing.Size(689, 405);
            this.tabAddProduct.TabIndex = 4;
            this.tabAddProduct.Text = "Agregar Producto";
            this.btnAgreagarProducto.BackColor = System.Drawing.Color.FromArgb(((int) (((byte) (192)))), ((int) (((byte) (0)))), ((int) (((byte) (192)))));
            this.btnAgreagarProducto.Font = new System.Drawing.Font("Microsoft Sans Serif", 9.75F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte) (0)));
            this.btnAgreagarProducto.ForeColor = System.Drawing.Color.White;
            this.btnAgreagarProducto.Location = new System.Drawing.Point(307, 300);
            this.btnAgreagarProducto.Name = "btnAgreagarProducto";
            this.btnAgreagarProducto.Size = new System.Drawing.Size(202, 57);
            this.btnAgreagarProducto.TabIndex = 12;
            this.btnAgreagarProducto.Text = "Agregar Producto";
            this.btnAgreagarProducto.UseVisualStyleBackColor = false;
            this.btnAgreagarProducto.Click += new System.EventHandler(this.btnAgreagarProducto_Click_1);
            this.txtNombreProducto.Location = new System.Drawing.Point(251, 160);
            this.txtNombreProducto.Name = "txtNombreProducto";
            this.txtNombreProducto.Size = new System.Drawing.Size(355, 20);
            this.txtNombreProducto.TabIndex = 10;
            this.label8.Font = new System.Drawing.Font("Microsoft Sans Serif", 14.25F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte) (0)));
            this.label8.ForeColor = System.Drawing.Color.White;
            this.label8.Location = new System.Drawing.Point(15, 160);
            this.label8.Name = "label8";
            this.label8.Size = new System.Drawing.Size(199, 40);
            this.label8.TabIndex = 9;
            this.label8.Text = "Nombre del Producto:";
            this.cmbAddProduct.FormattingEnabled = true;
            this.cmbAddProduct.Location = new System.Drawing.Point(251, 62);
            this.cmbAddProduct.Name = "cmbAddProduct";
            this.cmbAddProduct.Size = new System.Drawing.Size(355, 21);
            this.cmbAddProduct.TabIndex = 8;
            this.label7.Font = new System.Drawing.Font("Microsoft Sans Serif", 14.25F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte) (0)));
            this.label7.ForeColor = System.Drawing.Color.White;
            this.label7.Location = new System.Drawing.Point(32, 57);
            this.label7.Name = "label7";
            this.label7.Size = new System.Drawing.Size(199, 40);
            this.label7.TabIndex = 7;
            this.label7.Text = "Id del Negocio:";
            this.tabDeleteProduct.BackColor = System.Drawing.Color.FromArgb(((int) (((byte) (255)))), ((int) (((byte) (128)))), ((int) (((byte) (255)))));
            this.tabDeleteProduct.Controls.Add(this.combEliminarProd);
            this.tabDeleteProduct.Controls.Add(this.dgvVerProductos);
            this.tabDeleteProduct.Controls.Add(this.btnEliminarProducto);
            this.tabDeleteProduct.Controls.Add(this.label9);
            this.tabDeleteProduct.Location = new System.Drawing.Point(4, 22);
            this.tabDeleteProduct.Name = "tabDeleteProduct";
            this.tabDeleteProduct.Padding = new System.Windows.Forms.Padding(3);
            this.tabDeleteProduct.Size = new System.Drawing.Size(689, 405);
            this.tabDeleteProduct.TabIndex = 5;
            this.tabDeleteProduct.Text = "Eliminar Producto";
            this.combEliminarProd.FormattingEnabled = true;
            this.combEliminarProd.Location = new System.Drawing.Point(207, 29);
            this.combEliminarProd.Name = "combEliminarProd";
            this.combEliminarProd.Size = new System.Drawing.Size(355, 21);
            this.combEliminarProd.TabIndex = 14;
            this.dgvVerProductos.AllowUserToAddRows = false;
            this.dgvVerProductos.AllowUserToDeleteRows = false;
            this.dgvVerProductos.ColumnHeadersHeightSizeMode = System.Windows.Forms.DataGridViewColumnHeadersHeightSizeMode.AutoSize;
            this.dgvVerProductos.Location = new System.Drawing.Point(1, 137);
            this.dgvVerProductos.Name = "dgvVerProductos";
            this.dgvVerProductos.ReadOnly = true;
            this.dgvVerProductos.Size = new System.Drawing.Size(695, 272);
            this.dgvVerProductos.TabIndex = 13;
            this.btnEliminarProducto.BackColor = System.Drawing.Color.FromArgb(((int) (((byte) (192)))), ((int) (((byte) (0)))), ((int) (((byte) (192)))));
            this.btnEliminarProducto.Font = new System.Drawing.Font("Microsoft Sans Serif", 9.75F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte) (0)));
            this.btnEliminarProducto.ForeColor = System.Drawing.Color.White;
            this.btnEliminarProducto.Location = new System.Drawing.Point(278, 74);
            this.btnEliminarProducto.Name = "btnEliminarProducto";
            this.btnEliminarProducto.Size = new System.Drawing.Size(202, 57);
            this.btnEliminarProducto.TabIndex = 12;
            this.btnEliminarProducto.Text = "Eliminar Producto";
            this.btnEliminarProducto.UseVisualStyleBackColor = false;
            this.btnEliminarProducto.Click += new System.EventHandler(this.btnEliminarProducto_Click);
            this.label9.Font = new System.Drawing.Font("Microsoft Sans Serif", 14.25F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte) (0)));
            this.label9.ForeColor = System.Drawing.Color.White;
            this.label9.Location = new System.Drawing.Point(20, 29);
            this.label9.Name = "label9";
            this.label9.Size = new System.Drawing.Size(181, 40);
            this.label9.TabIndex = 7;
            this.label9.Text = "Id de Producto:";
            this.tabSeeOrders.BackColor = System.Drawing.Color.FromArgb(((int) (((byte) (255)))), ((int) (((byte) (128)))), ((int) (((byte) (255)))));
            this.tabSeeOrders.Controls.Add(this.dgvVerOrdenes);
            this.tabSeeOrders.Location = new System.Drawing.Point(4, 22);
            this.tabSeeOrders.Name = "tabSeeOrders";
            this.tabSeeOrders.Padding = new System.Windows.Forms.Padding(3);
            this.tabSeeOrders.Size = new System.Drawing.Size(689, 405);
            this.tabSeeOrders.TabIndex = 6;
            this.tabSeeOrders.Text = "Ver Ordenes";
            this.dgvVerOrdenes.AllowUserToAddRows = false;
            this.dgvVerOrdenes.AllowUserToDeleteRows = false;
            this.dgvVerOrdenes.ColumnHeadersHeightSizeMode = System.Windows.Forms.DataGridViewColumnHeadersHeightSizeMode.AutoSize;
            this.dgvVerOrdenes.Dock = System.Windows.Forms.DockStyle.Fill;
            this.dgvVerOrdenes.Location = new System.Drawing.Point(3, 3);
            this.dgvVerOrdenes.Name = "dgvVerOrdenes";
            this.dgvVerOrdenes.ReadOnly = true;
            this.dgvVerOrdenes.Size = new System.Drawing.Size(683, 399);
            this.dgvVerOrdenes.TabIndex = 14;
            this.tabAddAdress.BackColor = System.Drawing.Color.FromArgb(((int) (((byte) (255)))), ((int) (((byte) (128)))), ((int) (((byte) (255)))));
            this.tabAddAdress.Controls.Add(this.dgvVerDirecciones);
            this.tabAddAdress.Controls.Add(this.btnAgregarDireccion);
            this.tabAddAdress.Controls.Add(this.txtDireccion);
            this.tabAddAdress.Controls.Add(this.label10);
            this.tabAddAdress.Location = new System.Drawing.Point(4, 22);
            this.tabAddAdress.Name = "tabAddAdress";
            this.tabAddAdress.Size = new System.Drawing.Size(689, 405);
            this.tabAddAdress.TabIndex = 7;
            this.tabAddAdress.Text = "Agregar Dirección";
            this.dgvVerDirecciones.AllowUserToAddRows = false;
            this.dgvVerDirecciones.AllowUserToDeleteRows = false;
            this.dgvVerDirecciones.ColumnHeadersHeightSizeMode = System.Windows.Forms.DataGridViewColumnHeadersHeightSizeMode.AutoSize;
            this.dgvVerDirecciones.Location = new System.Drawing.Point(0, 137);
            this.dgvVerDirecciones.Name = "dgvVerDirecciones";
            this.dgvVerDirecciones.ReadOnly = true;
            this.dgvVerDirecciones.Size = new System.Drawing.Size(696, 268);
            this.dgvVerDirecciones.TabIndex = 14;
            this.btnAgregarDireccion.BackColor = System.Drawing.Color.FromArgb(((int) (((byte) (192)))), ((int) (((byte) (0)))), ((int) (((byte) (192)))));
            this.btnAgregarDireccion.Font = new System.Drawing.Font("Microsoft Sans Serif", 9.75F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte) (0)));
            this.btnAgregarDireccion.ForeColor = System.Drawing.Color.White;
            this.btnAgregarDireccion.Location = new System.Drawing.Point(293, 80);
            this.btnAgregarDireccion.Name = "btnAgregarDireccion";
            this.btnAgregarDireccion.Size = new System.Drawing.Size(202, 51);
            this.btnAgregarDireccion.TabIndex = 13;
            this.btnAgregarDireccion.Text = "Agregar Dirección";
            this.btnAgregarDireccion.UseVisualStyleBackColor = false;
            this.btnAgregarDireccion.Click += new System.EventHandler(this.btnAgregarDireccion_Click);
            this.txtDireccion.Location = new System.Drawing.Point(245, 35);
            this.txtDireccion.Name = "txtDireccion";
            this.txtDireccion.Size = new System.Drawing.Size(406, 20);
            this.txtDireccion.TabIndex = 9;
            this.label10.Font = new System.Drawing.Font("Microsoft Sans Serif", 14.25F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte) (0)));
            this.label10.ForeColor = System.Drawing.Color.White;
            this.label10.Location = new System.Drawing.Point(24, 30);
            this.label10.Name = "label10";
            this.label10.Size = new System.Drawing.Size(203, 40);
            this.label10.TabIndex = 8;
            this.label10.Text = "Ingrese su dirección:";
            this.tabModifyAdress.BackColor = System.Drawing.Color.FromArgb(((int) (((byte) (255)))), ((int) (((byte) (128)))), ((int) (((byte) (255)))));
            this.tabModifyAdress.Controls.Add(this.btnEliminarDirec);
            this.tabModifyAdress.Controls.Add(this.txtEliminarDirec);
            this.tabModifyAdress.Controls.Add(this.label13);
            this.tabModifyAdress.Controls.Add(this.btnMofificarDirec);
            this.tabModifyAdress.Controls.Add(this.label12);
            this.tabModifyAdress.Controls.Add(this.txtNuevaDirec);
            this.tabModifyAdress.Controls.Add(this.txtModificarDireccion);
            this.tabModifyAdress.Controls.Add(this.label11);
            this.tabModifyAdress.Location = new System.Drawing.Point(4, 22);
            this.tabModifyAdress.Name = "tabModifyAdress";
            this.tabModifyAdress.Size = new System.Drawing.Size(689, 405);
            this.tabModifyAdress.TabIndex = 8;
            this.tabModifyAdress.Text = "Modificar Dirección";
            this.btnEliminarDirec.BackColor = System.Drawing.Color.FromArgb(((int) (((byte) (192)))), ((int) (((byte) (0)))), ((int) (((byte) (192)))));
            this.btnEliminarDirec.Font = new System.Drawing.Font("Microsoft Sans Serif", 9.75F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte) (0)));
            this.btnEliminarDirec.ForeColor = System.Drawing.Color.White;
            this.btnEliminarDirec.Location = new System.Drawing.Point(267, 293);
            this.btnEliminarDirec.Name = "btnEliminarDirec";
            this.btnEliminarDirec.Size = new System.Drawing.Size(202, 51);
            this.btnEliminarDirec.TabIndex = 17;
            this.btnEliminarDirec.Text = "Eliminar Dirección";
            this.btnEliminarDirec.UseVisualStyleBackColor = false;
            this.btnEliminarDirec.Click += new System.EventHandler(this.btnEliminarDirec_Click);
            this.txtEliminarDirec.Location = new System.Drawing.Point(205, 247);
            this.txtEliminarDirec.Name = "txtEliminarDirec";
            this.txtEliminarDirec.Size = new System.Drawing.Size(406, 20);
            this.txtEliminarDirec.TabIndex = 16;
            this.label13.Font = new System.Drawing.Font("Microsoft Sans Serif", 14.25F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte) (0)));
            this.label13.ForeColor = System.Drawing.Color.White;
            this.label13.Location = new System.Drawing.Point(19, 242);
            this.label13.Name = "label13";
            this.label13.Size = new System.Drawing.Size(180, 40);
            this.label13.TabIndex = 15;
            this.label13.Text = "Id de su dirección:";
            this.btnMofificarDirec.BackColor = System.Drawing.Color.FromArgb(((int) (((byte) (192)))), ((int) (((byte) (0)))), ((int) (((byte) (192)))));
            this.btnMofificarDirec.Font = new System.Drawing.Font("Microsoft Sans Serif", 9.75F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte) (0)));
            this.btnMofificarDirec.ForeColor = System.Drawing.Color.White;
            this.btnMofificarDirec.Location = new System.Drawing.Point(279, 142);
            this.btnMofificarDirec.Name = "btnMofificarDirec";
            this.btnMofificarDirec.Size = new System.Drawing.Size(202, 51);
            this.btnMofificarDirec.TabIndex = 14;
            this.btnMofificarDirec.Text = "Modificar Dirección";
            this.btnMofificarDirec.UseVisualStyleBackColor = false;
            this.btnMofificarDirec.Click += new System.EventHandler(this.btnMofificarDirec_Click);
            this.label12.Font = new System.Drawing.Font("Microsoft Sans Serif", 14.25F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte) (0)));
            this.label12.ForeColor = System.Drawing.Color.White;
            this.label12.Location = new System.Drawing.Point(19, 97);
            this.label12.Name = "label12";
            this.label12.Size = new System.Drawing.Size(180, 40);
            this.label12.TabIndex = 12;
            this.label12.Text = "Nueva dirección:";
            this.txtNuevaDirec.Location = new System.Drawing.Point(205, 102);
            this.txtNuevaDirec.Name = "txtNuevaDirec";
            this.txtNuevaDirec.Size = new System.Drawing.Size(406, 20);
            this.txtNuevaDirec.TabIndex = 11;
            this.txtModificarDireccion.Location = new System.Drawing.Point(205, 34);
            this.txtModificarDireccion.Name = "txtModificarDireccion";
            this.txtModificarDireccion.Size = new System.Drawing.Size(406, 20);
            this.txtModificarDireccion.TabIndex = 10;
            this.label11.Font = new System.Drawing.Font("Microsoft Sans Serif", 14.25F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte) (0)));
            this.label11.ForeColor = System.Drawing.Color.White;
            this.label11.Location = new System.Drawing.Point(19, 29);
            this.label11.Name = "label11";
            this.label11.Size = new System.Drawing.Size(180, 40);
            this.label11.TabIndex = 9;
            this.label11.Text = "Id de su dirección:";
            this.tabAddOrder.BackColor = System.Drawing.Color.FromArgb(((int) (((byte) (255)))), ((int) (((byte) (128)))), ((int) (((byte) (255)))));
            this.tabAddOrder.Controls.Add(this.btnAgregarOrden);
            this.tabAddOrder.Controls.Add(this.cmbAgregarProd);
            this.tabAddOrder.Controls.Add(this.label15);
            this.tabAddOrder.Controls.Add(this.txtAgregarOrden);
            this.tabAddOrder.Controls.Add(this.label14);
            this.tabAddOrder.Location = new System.Drawing.Point(4, 22);
            this.tabAddOrder.Name = "tabAddOrder";
            this.tabAddOrder.Size = new System.Drawing.Size(689, 405);
            this.tabAddOrder.TabIndex = 9;
            this.tabAddOrder.Text = "Agregar Orden";
            this.btnAgregarOrden.BackColor = System.Drawing.Color.FromArgb(((int) (((byte) (192)))), ((int) (((byte) (0)))), ((int) (((byte) (192)))));
            this.btnAgregarOrden.Font = new System.Drawing.Font("Microsoft Sans Serif", 9.75F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte) (0)));
            this.btnAgregarOrden.ForeColor = System.Drawing.Color.White;
            this.btnAgregarOrden.Location = new System.Drawing.Point(285, 258);
            this.btnAgregarOrden.Name = "btnAgregarOrden";
            this.btnAgregarOrden.Size = new System.Drawing.Size(202, 51);
            this.btnAgregarOrden.TabIndex = 16;
            this.btnAgregarOrden.Text = "Agregar Orden";
            this.btnAgregarOrden.UseVisualStyleBackColor = false;
            this.btnAgregarOrden.Click += new System.EventHandler(this.btnAgregarOrden_Click);
            this.cmbAgregarProd.FormattingEnabled = true;
            this.cmbAgregarProd.Location = new System.Drawing.Point(217, 144);
            this.cmbAgregarProd.Name = "cmbAgregarProd";
            this.cmbAgregarProd.Size = new System.Drawing.Size(374, 21);
            this.cmbAgregarProd.TabIndex = 15;
            this.label15.Font = new System.Drawing.Font("Microsoft Sans Serif", 14.25F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte) (0)));
            this.label15.ForeColor = System.Drawing.Color.White;
            this.label15.Location = new System.Drawing.Point(22, 139);
            this.label15.Name = "label15";
            this.label15.Size = new System.Drawing.Size(180, 40);
            this.label15.TabIndex = 12;
            this.label15.Text = "Id de Producto :";
            this.txtAgregarOrden.Location = new System.Drawing.Point(217, 42);
            this.txtAgregarOrden.Name = "txtAgregarOrden";
            this.txtAgregarOrden.Size = new System.Drawing.Size(374, 20);
            this.txtAgregarOrden.TabIndex = 11;
            this.label14.Font = new System.Drawing.Font("Microsoft Sans Serif", 14.25F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte) (0)));
            this.label14.ForeColor = System.Drawing.Color.White;
            this.label14.Location = new System.Drawing.Point(22, 37);
            this.label14.Name = "label14";
            this.label14.Size = new System.Drawing.Size(180, 40);
            this.label14.TabIndex = 10;
            this.label14.Text = "Id de su dirección:";
            this.tabDeleteOrder.BackColor = System.Drawing.Color.FromArgb(((int) (((byte) (255)))), ((int) (((byte) (128)))), ((int) (((byte) (255)))));
            this.tabDeleteOrder.Controls.Add(this.textBox1);
            this.tabDeleteOrder.Controls.Add(this.dgvVerOrdenesPersonales);
            this.tabDeleteOrder.Controls.Add(this.btnEliminarOrden);
            this.tabDeleteOrder.Controls.Add(this.label16);
            this.tabDeleteOrder.Location = new System.Drawing.Point(4, 22);
            this.tabDeleteOrder.Name = "tabDeleteOrder";
            this.tabDeleteOrder.Size = new System.Drawing.Size(689, 405);
            this.tabDeleteOrder.TabIndex = 10;
            this.tabDeleteOrder.Text = "Eliminar Orden";
            this.dgvVerOrdenesPersonales.AllowUserToAddRows = false;
            this.dgvVerOrdenesPersonales.AllowUserToDeleteRows = false;
            this.dgvVerOrdenesPersonales.ColumnHeadersHeightSizeMode = System.Windows.Forms.DataGridViewColumnHeadersHeightSizeMode.AutoSize;
            this.dgvVerOrdenesPersonales.Location = new System.Drawing.Point(0, 134);
            this.dgvVerOrdenesPersonales.Name = "dgvVerOrdenesPersonales";
            this.dgvVerOrdenesPersonales.ReadOnly = true;
            this.dgvVerOrdenesPersonales.Size = new System.Drawing.Size(704, 275);
            this.dgvVerOrdenesPersonales.TabIndex = 18;
            this.btnEliminarOrden.BackColor = System.Drawing.Color.FromArgb(((int) (((byte) (192)))), ((int) (((byte) (0)))), ((int) (((byte) (192)))));
            this.btnEliminarOrden.Font = new System.Drawing.Font("Microsoft Sans Serif", 9.75F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte) (0)));
            this.btnEliminarOrden.ForeColor = System.Drawing.Color.White;
            this.btnEliminarOrden.Location = new System.Drawing.Point(282, 72);
            this.btnEliminarOrden.Name = "btnEliminarOrden";
            this.btnEliminarOrden.Size = new System.Drawing.Size(202, 51);
            this.btnEliminarOrden.TabIndex = 17;
            this.btnEliminarOrden.Text = "Eliminar Orden";
            this.btnEliminarOrden.UseVisualStyleBackColor = false;
            this.btnEliminarOrden.Click += new System.EventHandler(this.btnEliminarOrden_Click);
            this.label16.Font = new System.Drawing.Font("Microsoft Sans Serif", 14.25F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte) (0)));
            this.label16.ForeColor = System.Drawing.Color.White;
            this.label16.Location = new System.Drawing.Point(28, 35);
            this.label16.Name = "label16";
            this.label16.Size = new System.Drawing.Size(180, 40);
            this.label16.TabIndex = 11;
            this.label16.Text = "Id de su Orden:";
            this.textBox1.Location = new System.Drawing.Point(214, 35);
            this.textBox1.Name = "textBox1";
            this.textBox1.Size = new System.Drawing.Size(374, 20);
            this.textBox1.TabIndex = 19;
            this.AutoScaleDimensions = new System.Drawing.SizeF(6F, 13F);
            this.AutoScaleMode = System.Windows.Forms.AutoScaleMode.Font;
            this.ClientSize = new System.Drawing.Size(707, 434);
            this.Controls.Add(this.tabControl1);
            this.FormBorderStyle = System.Windows.Forms.FormBorderStyle.FixedSingle;
            this.MaximizeBox = false;
            this.Name = "Form1";
            this.Text = "HUGO";
            this.FormClosing += new System.Windows.Forms.FormClosingEventHandler(this.Form1_FormClosing);
            this.FormClosed += new System.Windows.Forms.FormClosedEventHandler(this.Form1_FormClosed);
            this.Load += new System.EventHandler(this.Form1_Load);
            this.tabControl1.ResumeLayout(false);
            this.tabAddUsu.ResumeLayout(false);
            this.tabAddUsu.PerformLayout();
            this.groupBox1.ResumeLayout(false);
            this.tabDeleteUsu.ResumeLayout(false);
            ((System.ComponentModel.ISupportInitialize) (this.dgvVerUsuarios)).EndInit();
            this.tabAddBussines.ResumeLayout(false);
            this.tabAddBussines.PerformLayout();
            this.tabDeleteBussines.ResumeLayout(false);
            ((System.ComponentModel.ISupportInitialize) (this.dataGridView1)).EndInit();
            this.tabAddProduct.ResumeLayout(false);
            this.tabAddProduct.PerformLayout();
            this.tabDeleteProduct.ResumeLayout(false);
            ((System.ComponentModel.ISupportInitialize) (this.dgvVerProductos)).EndInit();
            this.tabSeeOrders.ResumeLayout(false);
            ((System.ComponentModel.ISupportInitialize) (this.dgvVerOrdenes)).EndInit();
            this.tabAddAdress.ResumeLayout(false);
            this.tabAddAdress.PerformLayout();
            ((System.ComponentModel.ISupportInitialize) (this.dgvVerDirecciones)).EndInit();
            this.tabModifyAdress.ResumeLayout(false);
            this.tabModifyAdress.PerformLayout();
            this.tabAddOrder.ResumeLayout(false);
            this.tabAddOrder.PerformLayout();
            this.tabDeleteOrder.ResumeLayout(false);
            this.tabDeleteOrder.PerformLayout();
            ((System.ComponentModel.ISupportInitialize) (this.dgvVerOrdenesPersonales)).EndInit();
            this.ResumeLayout(false);
        }

        private System.Windows.Forms.Button btnAgreagarProducto;
        private System.Windows.Forms.Button btnAgregarDireccion;
        private System.Windows.Forms.Button btnAgregarNegocio;
        private System.Windows.Forms.Button btnAgregarOrden;
        private System.Windows.Forms.Button btnAgregarUsu;
        private System.Windows.Forms.Button btnEliminarDirec;
        private System.Windows.Forms.Button btnEliminarNegocio;
        private System.Windows.Forms.Button btnEliminarOrden;
        private System.Windows.Forms.Button btnEliminarProducto;
        private System.Windows.Forms.Button btnEliminarUsu;
        private System.Windows.Forms.Button btnMofificarDirec;
        private System.Windows.Forms.ComboBox cmbAddProduct;
        private System.Windows.Forms.ComboBox cmbAgregarProd;
        private System.Windows.Forms.ComboBox cmbEliminarNegocio;
        private System.Windows.Forms.ComboBox cmbEliminarUsu;
        private System.Windows.Forms.ComboBox combEliminarProd;
        private System.Windows.Forms.DataGridView dataGridView1;
        private System.Windows.Forms.DataGridView dgvVerDirecciones;
        private System.Windows.Forms.DataGridView dgvVerOrdenes;
        private System.Windows.Forms.DataGridView dgvVerOrdenesPersonales;
        private System.Windows.Forms.DataGridView dgvVerProductos;
        private System.Windows.Forms.DataGridView dgvVerUsuarios;
        private System.Windows.Forms.GroupBox groupBox1;
        private System.Windows.Forms.Label label1;
        private System.Windows.Forms.Label label10;
        private System.Windows.Forms.Label label11;
        private System.Windows.Forms.Label label12;
        private System.Windows.Forms.Label label13;
        private System.Windows.Forms.Label label14;
        private System.Windows.Forms.Label label15;
        private System.Windows.Forms.Label label16;
        private System.Windows.Forms.Label label2;
        private System.Windows.Forms.Label label3;
        private System.Windows.Forms.Label label4;
        private System.Windows.Forms.Label label5;
        private System.Windows.Forms.Label label6;
        private System.Windows.Forms.Label label7;
        private System.Windows.Forms.Label label8;
        private System.Windows.Forms.Label label9;
        private System.Windows.Forms.RadioButton rdbAdmin;
        private System.Windows.Forms.RadioButton rdbUsuario;
        private System.Windows.Forms.TabPage tabAddAdress;
        private System.Windows.Forms.TabPage tabAddBussines;
        private System.Windows.Forms.TabPage tabAddOrder;
        private System.Windows.Forms.TabPage tabAddProduct;
        private System.Windows.Forms.TabPage tabAddUsu;
        private System.Windows.Forms.TabControl tabControl1;
        private System.Windows.Forms.TabPage tabDeleteBussines;
        private System.Windows.Forms.TabPage tabDeleteOrder;
        private System.Windows.Forms.TabPage tabDeleteProduct;
        private System.Windows.Forms.TabPage tabDeleteUsu;
        private System.Windows.Forms.TabPage tabModifyAdress;
        private System.Windows.Forms.TabPage tabSeeOrders;
        private System.Windows.Forms.TextBox textBox1;
        private System.Windows.Forms.TextBox txtAgregarOrden;
        private System.Windows.Forms.TextBox txtDescripcion;
        private System.Windows.Forms.TextBox txtDireccion;
        private System.Windows.Forms.TextBox txtEliminarDirec;
        private System.Windows.Forms.TextBox txtFullname;
        private System.Windows.Forms.TextBox txtModificarDireccion;
        private System.Windows.Forms.TextBox txtNegocio;
        private System.Windows.Forms.TextBox txtNombreProducto;
        private System.Windows.Forms.TextBox txtNuevaDirec;
        private System.Windows.Forms.TextBox txtUserName;

        private System.Windows.Forms.DataGridView dataGridView2;
        private System.Windows.Forms.DataGridView dgtVerProductos;

        #endregion
    }
}